name: 'prettier-format-suggestion'
description: 'This action will report any prettier format issue and propose you, if you want to fix them, to us configured triggers to do that automatically'
author: 'takanome-dev'
# TODO: update this
branding:
  icon: 'activity'
  color: 'white'
runs:
  using: 'node16'
  main: 'dist/index.js'

inputs:
  github_token:
    default: ${{ github.token }}
    required: true
  trigger:
    description: The comment that triggers the action
    default: yes