name: Prettify Action
description: ' GitHub action that suggests formatting changes with Prettier on pull requests, making it easier to maintain consistent code style and readability '
author: 'TAKANOME-DEV'

# TODO: update this
branding:
  icon: 'activity'
  color: 'white'
runs:
  using: 'node16'
  main: 'dist/index.js'

inputs:
  github_token:
    default: ${{ github.token }}
    required: true
  trigger:
    description: The comment that triggers the action
    default: 'yes'
  files:
    description: 'Files to format'
    default: 'js,jsx,ts,tsx,css,scss,md'
  label:
    description: 'Label to add to the PR to indicate that it has not been formatted'
    default: '🚨 Prettier Format'
  pr_body:
    description: PullRequest body.
    required: false
    default: |
      ## :warning: Prettier Format Suggestion :warning:

      This PR is a suggestion to format your code using [Prettier](https://prettier.io/).
      There are some files that are not formatted correctly, so I suggest you to use Prettier to format them.

      Currently, the following files are not formatted correctly:

      {{#files}}
      - {{.}}
      {{/files}}

      If you want to format them, check the box below and a commit will be added to this PR with the formatted files.

      - [ ] I want to format the files


      <details>
      <summary>Click here to see the formatted files</summary>

      {{#formattedFiles}}
      - {{.}}
      {{/formattedFiles}}

      </details>      

      <hr>

      [:octocat: Repo](${ACTION_URL}) | [:memo: Issues](${ACTION_URL}/issues) | [:department_store: Marketplace](${ACTION_MARKETPLACE_URL})
